
/* First created by JCasGen Sat Oct 18 19:40:19 EDT 2014 */
package edu.cmu.lti.oaqa.type.answer;

import org.apache.uima.jcas.JCas;
import org.apache.uima.jcas.JCasRegistry;
import org.apache.uima.cas.impl.CASImpl;
import org.apache.uima.cas.impl.FSGenerator;
import org.apache.uima.cas.FeatureStructure;
import org.apache.uima.cas.impl.TypeImpl;
import org.apache.uima.cas.Type;
import org.apache.uima.cas.impl.FeatureImpl;
import org.apache.uima.cas.Feature;
import org.apache.uima.jcas.cas.TOP_Type;

/** An exact answer text generated by the QA system.
 * Updated by JCasGen Tue Dec 02 00:06:35 EST 2014
 * @generated */
public class Answer_Type extends TOP_Type {
  /** @generated 
   * @return the generator for this type
   */
  @Override
  protected FSGenerator getFSGenerator() {return fsGenerator;}
  /** @generated */
  private final FSGenerator fsGenerator = 
    new FSGenerator() {
      public FeatureStructure createFS(int addr, CASImpl cas) {
  			 if (Answer_Type.this.useExistingInstance) {
  			   // Return eq fs instance if already created
  		     FeatureStructure fs = Answer_Type.this.jcas.getJfsFromCaddr(addr);
  		     if (null == fs) {
  		       fs = new Answer(addr, Answer_Type.this);
  			   Answer_Type.this.jcas.putJfsFromCaddr(addr, fs);
  			   return fs;
  		     }
  		     return fs;
        } else return new Answer(addr, Answer_Type.this);
  	  }
    };
  /** @generated */
  @SuppressWarnings ("hiding")
  public final static int typeIndexID = Answer.typeIndexID;
  /** @generated 
     @modifiable */
  @SuppressWarnings ("hiding")
  public final static boolean featOkTst = JCasRegistry.getFeatOkTst("edu.cmu.lti.oaqa.type.answer.Answer");
 
  /** @generated */
  final Feature casFeat_text;
  /** @generated */
  final int     casFeatCode_text;
  /** @generated
   * @param addr low level Feature Structure reference
   * @return the feature value 
   */ 
  public String getText(int addr) {
        if (featOkTst && casFeat_text == null)
      jcas.throwFeatMissing("text", "edu.cmu.lti.oaqa.type.answer.Answer");
    return ll_cas.ll_getStringValue(addr, casFeatCode_text);
  }
  /** @generated
   * @param addr low level Feature Structure reference
   * @param v value to set 
   */    
  public void setText(int addr, String v) {
        if (featOkTst && casFeat_text == null)
      jcas.throwFeatMissing("text", "edu.cmu.lti.oaqa.type.answer.Answer");
    ll_cas.ll_setStringValue(addr, casFeatCode_text, v);}
    
  
 
  /** @generated */
  final Feature casFeat_variants;
  /** @generated */
  final int     casFeatCode_variants;
  /** @generated
   * @param addr low level Feature Structure reference
   * @return the feature value 
   */ 
  public int getVariants(int addr) {
        if (featOkTst && casFeat_variants == null)
      jcas.throwFeatMissing("variants", "edu.cmu.lti.oaqa.type.answer.Answer");
    return ll_cas.ll_getRefValue(addr, casFeatCode_variants);
  }
  /** @generated
   * @param addr low level Feature Structure reference
   * @param v value to set 
   */    
  public void setVariants(int addr, int v) {
        if (featOkTst && casFeat_variants == null)
      jcas.throwFeatMissing("variants", "edu.cmu.lti.oaqa.type.answer.Answer");
    ll_cas.ll_setRefValue(addr, casFeatCode_variants, v);}
    
  
 
  /** @generated */
  final Feature casFeat_rank;
  /** @generated */
  final int     casFeatCode_rank;
  /** @generated
   * @param addr low level Feature Structure reference
   * @return the feature value 
   */ 
  public int getRank(int addr) {
        if (featOkTst && casFeat_rank == null)
      jcas.throwFeatMissing("rank", "edu.cmu.lti.oaqa.type.answer.Answer");
    return ll_cas.ll_getIntValue(addr, casFeatCode_rank);
  }
  /** @generated
   * @param addr low level Feature Structure reference
   * @param v value to set 
   */    
  public void setRank(int addr, int v) {
        if (featOkTst && casFeat_rank == null)
      jcas.throwFeatMissing("rank", "edu.cmu.lti.oaqa.type.answer.Answer");
    ll_cas.ll_setIntValue(addr, casFeatCode_rank, v);}
    
  
 
  /** @generated */
  final Feature casFeat_docScore;
  /** @generated */
  final int     casFeatCode_docScore;
  /** @generated
   * @param addr low level Feature Structure reference
   * @return the feature value 
   */ 
  public double getDocScore(int addr) {
        if (featOkTst && casFeat_docScore == null)
      jcas.throwFeatMissing("docScore", "edu.cmu.lti.oaqa.type.answer.Answer");
    return ll_cas.ll_getDoubleValue(addr, casFeatCode_docScore);
  }
  /** @generated
   * @param addr low level Feature Structure reference
   * @param v value to set 
   */    
  public void setDocScore(int addr, double v) {
        if (featOkTst && casFeat_docScore == null)
      jcas.throwFeatMissing("docScore", "edu.cmu.lti.oaqa.type.answer.Answer");
    ll_cas.ll_setDoubleValue(addr, casFeatCode_docScore, v);}
    
  
 
  /** @generated */
  final Feature casFeat_posScore;
  /** @generated */
  final int     casFeatCode_posScore;
  /** @generated
   * @param addr low level Feature Structure reference
   * @return the feature value 
   */ 
  public double getPosScore(int addr) {
        if (featOkTst && casFeat_posScore == null)
      jcas.throwFeatMissing("posScore", "edu.cmu.lti.oaqa.type.answer.Answer");
    return ll_cas.ll_getDoubleValue(addr, casFeatCode_posScore);
  }
  /** @generated
   * @param addr low level Feature Structure reference
   * @param v value to set 
   */    
  public void setPosScore(int addr, double v) {
        if (featOkTst && casFeat_posScore == null)
      jcas.throwFeatMissing("posScore", "edu.cmu.lti.oaqa.type.answer.Answer");
    ll_cas.ll_setDoubleValue(addr, casFeatCode_posScore, v);}
    
  
 
  /** @generated */
  final Feature casFeat_negScore;
  /** @generated */
  final int     casFeatCode_negScore;
  /** @generated
   * @param addr low level Feature Structure reference
   * @return the feature value 
   */ 
  public double getNegScore(int addr) {
        if (featOkTst && casFeat_negScore == null)
      jcas.throwFeatMissing("negScore", "edu.cmu.lti.oaqa.type.answer.Answer");
    return ll_cas.ll_getDoubleValue(addr, casFeatCode_negScore);
  }
  /** @generated
   * @param addr low level Feature Structure reference
   * @param v value to set 
   */    
  public void setNegScore(int addr, double v) {
        if (featOkTst && casFeat_negScore == null)
      jcas.throwFeatMissing("negScore", "edu.cmu.lti.oaqa.type.answer.Answer");
    ll_cas.ll_setDoubleValue(addr, casFeatCode_negScore, v);}
    
  
 
  /** @generated */
  final Feature casFeat_sectionScore;
  /** @generated */
  final int     casFeatCode_sectionScore;
  /** @generated
   * @param addr low level Feature Structure reference
   * @return the feature value 
   */ 
  public double getSectionScore(int addr) {
        if (featOkTst && casFeat_sectionScore == null)
      jcas.throwFeatMissing("sectionScore", "edu.cmu.lti.oaqa.type.answer.Answer");
    return ll_cas.ll_getDoubleValue(addr, casFeatCode_sectionScore);
  }
  /** @generated
   * @param addr low level Feature Structure reference
   * @param v value to set 
   */    
  public void setSectionScore(int addr, double v) {
        if (featOkTst && casFeat_sectionScore == null)
      jcas.throwFeatMissing("sectionScore", "edu.cmu.lti.oaqa.type.answer.Answer");
    ll_cas.ll_setDoubleValue(addr, casFeatCode_sectionScore, v);}
    
  
 
  /** @generated */
  final Feature casFeat_goldAnswer;
  /** @generated */
  final int     casFeatCode_goldAnswer;
  /** @generated
   * @param addr low level Feature Structure reference
   * @return the feature value 
   */ 
  public double getGoldAnswer(int addr) {
        if (featOkTst && casFeat_goldAnswer == null)
      jcas.throwFeatMissing("goldAnswer", "edu.cmu.lti.oaqa.type.answer.Answer");
    return ll_cas.ll_getDoubleValue(addr, casFeatCode_goldAnswer);
  }
  /** @generated
   * @param addr low level Feature Structure reference
   * @param v value to set 
   */    
  public void setGoldAnswer(int addr, double v) {
        if (featOkTst && casFeat_goldAnswer == null)
      jcas.throwFeatMissing("goldAnswer", "edu.cmu.lti.oaqa.type.answer.Answer");
    ll_cas.ll_setDoubleValue(addr, casFeatCode_goldAnswer, v);}
    
  



  /** initialize variables to correspond with Cas Type and Features
	 * @generated
	 * @param jcas JCas
	 * @param casType Type 
	 */
  public Answer_Type(JCas jcas, Type casType) {
    super(jcas, casType);
    casImpl.getFSClassRegistry().addGeneratorForType((TypeImpl)this.casType, getFSGenerator());

 
    casFeat_text = jcas.getRequiredFeatureDE(casType, "text", "uima.cas.String", featOkTst);
    casFeatCode_text  = (null == casFeat_text) ? JCas.INVALID_FEATURE_CODE : ((FeatureImpl)casFeat_text).getCode();

 
    casFeat_variants = jcas.getRequiredFeatureDE(casType, "variants", "uima.cas.StringList", featOkTst);
    casFeatCode_variants  = (null == casFeat_variants) ? JCas.INVALID_FEATURE_CODE : ((FeatureImpl)casFeat_variants).getCode();

 
    casFeat_rank = jcas.getRequiredFeatureDE(casType, "rank", "uima.cas.Integer", featOkTst);
    casFeatCode_rank  = (null == casFeat_rank) ? JCas.INVALID_FEATURE_CODE : ((FeatureImpl)casFeat_rank).getCode();

 
    casFeat_docScore = jcas.getRequiredFeatureDE(casType, "docScore", "uima.cas.Double", featOkTst);
    casFeatCode_docScore  = (null == casFeat_docScore) ? JCas.INVALID_FEATURE_CODE : ((FeatureImpl)casFeat_docScore).getCode();

 
    casFeat_posScore = jcas.getRequiredFeatureDE(casType, "posScore", "uima.cas.Double", featOkTst);
    casFeatCode_posScore  = (null == casFeat_posScore) ? JCas.INVALID_FEATURE_CODE : ((FeatureImpl)casFeat_posScore).getCode();

 
    casFeat_negScore = jcas.getRequiredFeatureDE(casType, "negScore", "uima.cas.Double", featOkTst);
    casFeatCode_negScore  = (null == casFeat_negScore) ? JCas.INVALID_FEATURE_CODE : ((FeatureImpl)casFeat_negScore).getCode();

 
    casFeat_sectionScore = jcas.getRequiredFeatureDE(casType, "sectionScore", "uima.cas.Double", featOkTst);
    casFeatCode_sectionScore  = (null == casFeat_sectionScore) ? JCas.INVALID_FEATURE_CODE : ((FeatureImpl)casFeat_sectionScore).getCode();

 
    casFeat_goldAnswer = jcas.getRequiredFeatureDE(casType, "goldAnswer", "uima.cas.Double", featOkTst);
    casFeatCode_goldAnswer  = (null == casFeat_goldAnswer) ? JCas.INVALID_FEATURE_CODE : ((FeatureImpl)casFeat_goldAnswer).getCode();

  }
}



    